### ISSUE TITLE
bs-react-native seems unused in this repo

### ISSUE THREAD

**Issue by MoOx** [Astrocoders/bs-react-native-vector-icons#5]
You can probably remove all reference to it, especially since you migrated to jsx3 :)

**Comment by fakenickels** [comment]
indeed! good catch
thanks

**Comment by Maushundb** [comment]
Still think you need to remove it from your bsconfig - https://github.com/Astrocoders/bs-react-native-vector-icons/blob/master/bsconfig.json#L7
